language: node_js
node_js:
  - "10"
  - "12"
  - "14"
before_script:
  - yarn run lint
install:
  - yarn install --ignore-engines
  - yarn global add codecov
script:
  - yarn run test
  - codecov
after_success:
  - yarn run semantic-release
